version: "3.3"
services:
  app:
    build: .
    container_name: article_management_api
    ports:
      - 9090:9090
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./rds-combined-ca-bundle.pem:/app/rds-combined-ca-bundle.pem
      - ./credentials.json:/app/credentials.json
